PLACES = [
    {
        "id": 1,
        "name": "Just Coffee",
        "category": "coffee",
        "district": "Центр",
        "address": "пр. Революции, 22",
        "lat": 51.6612,
        "lon": 39.2004,
        "avg_check": 700,
        "open_now": True,
        "tags": ["кофе", "десерт", "уютно", "быстро"],
        "scenarios": ["кофе", "десерт", "быстро", "рядом"],
        "description": "Спокойное место для кофе и десерта в центре.",
    },
    {
        "id": 2,
        "name": "Breakfast Room",
        "category": "breakfast",
        "district": "Центр",
        "address": "ул. Плехановская, 14",
        "lat": 51.6671,
        "lon": 39.1911,
        "avg_check": 1100,
        "open_now": True,
        "tags": ["завтрак", "уютно", "свидание", "красиво"],
        "scenarios": ["завтрак", "свидание", "красиво"],
        "description": "Красивые завтраки и спокойная атмосфера.",
    },
    {
        "id": 3,
        "name": "Pasta & Wine",
        "category": "dinner",
        "district": "Центр",
        "address": "ул. Кардашова, 6",
        "lat": 51.6605,
        "lon": 39.2042,
        "avg_check": 1500,
        "open_now": True,
        "tags": ["ужин", "романтично", "красиво", "вино"],
        "scenarios": ["ужин", "свидание", "красиво"],
        "description": "Подходит для ужина и свидания.",
    },
    {
        "id": 4,
        "name": "Burger Point",
        "category": "lunch",
        "district": "Северный",
        "address": "Московский проспект, 90",
        "lat": 51.7068,
        "lon": 39.1681,
        "avg_check": 900,
        "open_now": True,
        "tags": ["обед", "быстро", "недорого", "бургеры"],
        "scenarios": ["обед", "быстро", "до 1000"],
        "description": "Быстрый сытный обед без перегруза.",
    },
    {
        "id": 5,
        "name": "Family Kitchen",
        "category": "family",
        "district": "Левый берег",
        "address": "Ленинский проспект, 120",
        "lat": 51.6467,
        "lon": 39.2571,
        "avg_check": 1300,
        "open_now": True,
        "tags": ["семья", "дети", "ужин", "просторно"],
        "scenarios": ["семья", "с детьми", "ужин"],
        "description": "Удобно для семейного ужина и детей.",
    },
    {
        "id": 6,
        "name": "Late Bar",
        "category": "bar",
        "district": "Центр",
        "address": "ул. Комиссаржевской, 10",
        "lat": 51.6694,
        "lon": 39.1980,
        "avg_check": 1400,
        "open_now": True,
        "tags": ["бар", "вечер", "друзья", "шумно"],
        "scenarios": ["вечер", "с друзьями", "бар"],
        "description": "Для шумного вечера с друзьями.",
    },
]
